### PR TITLE
Bump dependencies and build on Go 1.13

### PR DESCRIPTION
**Pull request by int128**
This bumps version of the followings:

- go
- golangci-lint
- dependencies

### CODE REVIEW

**Comment by int128** [comment]
This will fix the issue on Go 1.13:

```
% go run main.go -h
# golang.org/x/xerrors
../../../go/pkg/mod/golang.org/x/xerrors@v0.0.0-20190513163551-3ee3066db522/adaptor_go1_13.go:16:14: undefined: errors.Frame
../../../go/pkg/mod/golang.org/x/xerrors@v0.0.0-20190513163551-3ee3066db522/format_go1_13.go:12:18: undefined: errors.Formatter
```
